//
//  token.swift
//  Compiler
//
//  Created by Livio Bieri on 30/09/15.
//  Copyright (c) 2015 Livio Bieri. All rights reserved.
//

import Foundation

enum Terminal: String{
	case LPARENT = "("
	case RPARENT = ")"
	case COMMA = ","
    case SEMI = ";"
    case COLON = ":"
    case BECOMES = ":="
	case TIMES = "*"
	case PLUS = "+"
	case MINUS = "-"
	case DIV = "div"
	case MOD = "mod"
	case EQ = "="
	case NE = "/="
	case LT = "<"
	case GT = ">"
	case LE = "<="
	case GE = ">="
	case AND = "&&"
	case OR = "||"
	case CAND = "&\\?"
	case COR = "|\\?"
	case BOOLTYPE = "bool"
	case INT32 = "int32"
	case CALL = "call"
	case CONST = "const"
	case VAR = "var"
	case COPY = "copy"
	case REF = "ref"
	case DEBUGIN = "debugin"
	case DEBUGOUT = "debugout"
	case DO = "do"
	case ELSE = "else"
	case ENDFUN = "endfun"
	case ENDIF = "endif"
	case ENDPROC = "endproc"
	case ENDPROGRAM = "endprogram"
	case ENDWHILE = "endwhile"
	case FALSE = "false"
	case TRUE = "true"
	case FUN = "fun"
	case GLOBAL = "global"
	case IF = "if"
	case IN = "in"
	case INOUT = "inout"
	case OUT = "out"
	case INIT = "init"
	case LOCAL = "local"
	case NOT = "!"
	case PROC = "proc"
	case PROGRAM = "program"
	case RETURNS = "returns"
	case SKIP = "skip"
	case THEN = "then"
	case WHILE = "while"
	case ASSERT = "assert"
	case PRE = "pre"
	case POST = "post"
	case INV = "inv"
	case OLD = "old"
	case IDENT = "[a-zA-Z][a-zA-Z0-9]*"
	case WS = "\\s+"
	case INTVAL32 = "[0-9]+"
	case COMMENT
	case BLOCKCOMMENT = "/\\*.*?\\*/"
	case LINECOMMENT = "//.*?\n"
}